import {FormEvent,ReactNode,useEffect,useMemo,useState} from 'react';
import {api,clearToken,getToken,saveSession,type DocumentItem,type Event,type Folder,type Group,type Notification,type User,type Version} from './services/api';
import {Button,Icon,Modal,StatePanel} from './components/ui';

type View='home'|'documents'|'viewer'|'editor'|'create'|'history'|'versions'|'folders'|'favorites'|'recent'|'trash'|'search'|'advanced-search'|'profile'|'users'|'groups'|'permissions'|'audit'|'admin'|'settings';
const nav:[View,string,string][]=[['home','Início','home'],['documents','Documentos','file'],['folders','Pastas','file'],['favorites','Favoritos','star'],['recent','Recentes','clock'],['trash','Lixeira','trash'],['search','Pesquisa','search'],['profile','Meu perfil','user'],['users','Usuários','user'],['groups','Grupos','user'],['permissions','Permissões','settings'],['audit','Auditoria','clock'],['admin','Administração','settings'],['settings','Configurações','settings']];

function Auth({done}:{done:(u:User)=>void}){const[recovery,setRecovery]=useState(false),[register,setRegister]=useState(false),[form,setForm]=useState({name:'',email:'',password:''}),[message,setMessage]=useState(''),[error,setError]=useState('');
async function submit(e:FormEvent){e.preventDefault();setError('');setMessage('');try{if(recovery){const r=await api.recovery(form.email);setMessage(r.message);return}const s=register?await api.register(form):await api.login({email:form.email,password:form.password});saveSession(s);done(s.user)}catch(x){setError(x instanceof Error?x.message:'Não foi possível concluir.')}}return <main className="auth-shell"><section className="auth-card"><div className="brand-mark">K</div><p className="eyebrow">KORCZAK TECHNOLOGIES</p><h1>Korczak <span>Documents</span></h1>{error&&<div className="alert alert-error">{error}</div>}{message&&<div className="alert">{message}</div>}<form onSubmit={submit}>{!recovery&&register&&<label>Nome<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label>}<label>E-mail<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/></label>{!recovery&&<label>Senha<input type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} minLength={12} required/></label>}<Button>{recovery?'Enviar recuperação':register?'Criar conta':'Entrar'}</Button></form><div className="auth-links"><button className="text-button" onClick={()=>setRecovery(!recovery)}>{recovery?'Voltar':'Recuperar acesso'}</button><button className="text-button" onClick={()=>{setRecovery(false);setRegister(!register)}}>{register?'Já tenho conta':'Criar conta'}</button></div></section></main>}

function Section({title,children,actions}:{title:string;children:ReactNode;actions?:ReactNode}){return <section className="panel"><div className="panel-head"><h2>{title}</h2>{actions}</div>{children}</section>}
function DocumentTable({docs,onSelect,onAction}:{docs:DocumentItem[];onSelect:(d:DocumentItem)=>void;onAction:(d:DocumentItem)=>void}){return docs.length?<div className="table-wrap"><table><thead><tr><th>Nome</th><th>Tipo</th><th>Atualizado</th><th>Status</th><th>Ação</th></tr></thead><tbody>{docs.map(d=><tr key={d.id}><td><button className="link-button" onClick={()=>onSelect(d)}><strong>{d.name}</strong></button></td><td>{d.document_type}</td><td>{new Date(d.updated_at).toLocaleString('pt-BR')}</td><td>{d.status==='deleted'?'Lixeira':'Ativo'}</td><td><button className="row-action" onClick={()=>onAction(d)}>{d.status==='deleted'?'↩':d.favorite?'★':'☆'}</button></td></tr>)}</tbody></table></div>:<StatePanel title="Nada por aqui" message="Nenhum documento encontrado."/>}

function App(){const[user,setUser]=useState<User|null>(null),[boot,setBoot]=useState(true),[view,setView]=useState<View>('home'),[docs,setDocs]=useState<DocumentItem[]>([]),[selected,setSelected]=useState<DocumentItem|null>(null),[versions,setVersions]=useState<Version[]>([]),[history,setHistory]=useState<Event[]>([]),[folders,setFolders]=useState<Folder[]>([]),[users,setUsers]=useState<User[]>([]),[groups,setGroups]=useState<Group[]>([]),[events,setEvents]=useState<Event[]>([]),[notes,setNotes]=useState<Notification[]>([]),[permissions,setPermissions]=useState<{role:string;actions:string[]}|null>(null),[query,setQuery]=useState(''),[error,setError]=useState(''),[modal,setModal]=useState(false),[editingFolder,setEditingFolder]=useState<Folder|null>(null),[theme,setTheme]=useState(localStorage.getItem('kz_theme')||'dark');

useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('kz_theme',theme)},[theme]);
useEffect(()=>{if(!getToken()){setBoot(false);return}api.me().then(setUser).catch(()=>clearToken()).finally(()=>setBoot(false))},[]);
useEffect(()=>{if(user)load(view)},[user,view]);

async function load(v:View=view){try{setError('');if(v==='home'||v==='documents')setDocs(await api.documents());if(v==='favorites')setDocs(await api.favorites());if(v==='trash')setDocs(await api.trash());if(v==='folders')setFolders(await api.folders());if(v==='recent')setDocs(await api.recent());if(v==='users'||v==='admin')setUsers(await api.users());if(v==='groups')setGroups(await api.groups());if(v==='audit')setEvents((await api.audit()).items);if(v==='home')setNotes(await api.notifications());if(v==='search'||v==='advanced-search')setDocs(await api.search(query))}catch(x){setError(x instanceof Error?x.message:'Falha ao carregar dados.')}}
async function openDoc(d:DocumentItem){try{const full=await api.document(d.id);setSelected(full);await api.open(d.id)}catch{}setView('viewer')}
async function showVersions(v:View){if(!selected)return;setVersions(await api.versions(selected.id));setView(v)}
async function showHistory(){if(!selected)return;setHistory((await api.audit(selected.id)).items);setView('history')}
async function editDocument(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;const f=new FormData(e.currentTarget);try{const name=String(f.get('name'));const type=String(f.get('type'));const content=String(f.get('content')||'');await api.updateDocument(selected.id,{name,document_type:type});if(content!==String(selected.content||''))await api.createVersion(selected.id,content);setSelected(await api.document(selected.id));setView('viewer')}catch(x){setError(x instanceof Error?x.message:'Não foi possível salvar.')}}
async function createDocument(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{const d=await api.createDocument({name:String(f.get('name')),document_type:String(f.get('type')),folder_id:String(f.get('folder')||'')||null,content:String(f.get('content')||'')});setModal(false);setSelected(await api.document(d.id));setView('viewer')}catch(x){setError(x instanceof Error?x.message:'Não foi possível criar.')}}
async function newVersion(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;const f=new FormData(e.currentTarget);try{await api.createVersion(selected.id,String(f.get('content')||''));setSelected(await api.document(selected.id));setVersions(await api.versions(selected.id));setView('versions')}catch(x){setError(x instanceof Error?x.message:'Não foi possível criar a versão.')}}
async function restoreVersion(v:Version){if(!selected)return;try{await api.restoreVersion(selected.id,v.id);setSelected(await api.document(selected.id));setVersions(await api.versions(selected.id));setView('viewer')}catch(x){setError(x instanceof Error?x.message:'Não foi possível restaurar a versão.')}}

if(boot)return <StatePanel title="Iniciando" message="Preparando o Korczak Documents…"/>;if(!user)return <Auth done={setUser}/>;
const shown=useMemo(()=>{if(view==='search'||view==='advanced-search')return docs.filter(d=>d.name.toLowerCase().includes(query.toLowerCase()));return docs},[docs,view,query]);
const title=nav.find(n=>n[0]===view)?.[1]||'Korczak Documents';
const action=async(d:DocumentItem)=>{try{if(d.status==='deleted')await api.restore(d.id);else await api.favorite(d.id,!d.favorite);await load(view)}catch(x){setError(x instanceof Error?x.message:'Operação não concluída.')}};
return <div className="app-shell"><aside className="sidebar"><div className="side-brand"><div className="brand-mark small">K</div><div><strong>Korczak</strong><span>Documents</span></div></div><nav>{nav.map(n=><button className={'nav-item '+(view===n[0]?'active':'')} onClick={()=>setView(n[0])} key={n[0]}><Icon name={n[2]}/><span>{n[1]}</span></button>)}</nav><div className="sidebar-bottom"><button className="nav-item" onClick={()=>{clearToken();setUser(null)}}>↪ Sair</button></div></aside><div className="main-shell"><header className="topbar"><div className="mobile-brand"><b>Korczak Documents</b></div><div className="top-search"><Icon name="search"/><input value={query} onChange={async e=>{const q=e.target.value;setQuery(q);setView('search');if(q.trim())setDocs(await api.search(q));else setDocs(await api.documents())}} placeholder="Pesquisar documentos…"/></div><button className="avatar" onClick={()=>setView('profile')}>{user.name[0]}</button></header><main className="content"><div className="page-head"><div><p className="eyebrow">KORCZAK DOCUMENTS</p><h1>{title}</h1></div>{(view==='documents'||view==='home')&&<Button onClick={()=>setModal(true)}><Icon name="plus"/>Novo documento</Button>}</div>{error&&<div className="alert alert-error">{error}<button onClick={()=>load(view)}>Tentar novamente</button></div>}

{view==='home'&&<><section className="dashboard-grid"><div className="welcome-card"><p className="eyebrow">DASHBOARD</p><h2>Olá, {user.name.split(' ')[0]}.</h2><p>Seu espaço de documentos em um só lugar.</p><Button onClick={()=>setModal(true)}>Criar documento</Button></div><div className="stat-card"><span>Documentos</span><strong>{docs.length}</strong></div><div className="stat-card"><span>Favoritos</span><strong>{docs.filter(d=>d.favorite).length}</strong></div><div className="stat-card"><span>Não lidas</span><strong>{notes.filter(n=>!n.read).length}</strong></div></section><Section title="Documentos recentes"><DocumentTable docs={docs.slice(0,8)} onSelect={openDoc} onAction={action}/></Section></>}

{(view==='documents'||view==='favorites'||view==='trash'||view==='recent')&&<Section title={title}><DocumentTable docs={docs} onSelect={openDoc} onAction={action}/></Section>}
{view==='search'&&<Section title="Pesquisa global"><DocumentTable docs={shown} onSelect={openDoc} onAction={action}/></Section>}
{view==='advanced-search'&&<Section title="Pesquisa avançada"><form className="advanced-grid" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const a={term:String(f.get('term')||''),folder:String(f.get('folder')||''),status:String(f.get('status')||''),from:String(f.get('from')||''),to:String(f.get('to')||''),sort:String(f.get('sort')||'updated_desc')};setAdvanced(a);setDocs(await api.advancedSearch(a));}}><label>Nome/conteúdo<input name="term" defaultValue={advanced.term}/></label><label>Pasta<select name="folder" defaultValue={advanced.folder}><option value="">Todas</option>{folders.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label>Estado<select name="status" defaultValue={advanced.status}><option value="">Ativos</option><option value="active">Ativo</option><option value="deleted">Lixeira</option></select></label><label>De<input type="date" name="from" defaultValue={advanced.from}/></label><label>Até<input type="date" name="to" defaultValue={advanced.to}/></label><label>Ordenação<select name="sort" defaultValue={advanced.sort}><option value="updated_desc">Atualização ↓</option><option value="updated_asc">Atualização ↑</option><option value="name_asc">Nome A–Z</option><option value="name_desc">Nome Z–A</option></select></label><Button type="submit">Pesquisar</Button></form><DocumentTable docs={docs} onSelect={openDoc} onAction={action}/></Section>}

{view==='viewer'&&selected&&<Section title={selected.name} actions={<Button variant="secondary" onClick={()=>setView('editor')}>Editar</Button>}><div className="document-toolbar"><Button variant="secondary" onClick={()=>showVersions('versions')}>Versionamento</Button><Button variant="secondary" onClick={showHistory}>Histórico</Button><Button variant="secondary" onClick={async()=>{setPermissions(await api.permissions(selected.id));setView('permissions')}}>Permissões</Button><Button variant="danger" onClick={async()=>{await api.deleteDocument(selected.id);setView('documents');load('documents')}}>Mover para lixeira</Button></div><article className="document-view"><p><strong>{selected.name}</strong> · {selected.document_type}</p><hr/><div className="document-content">{selected.content||'Este documento não possui conteúdo textual.'}</div></article></Section>}

{view==='editor'&&selected&&<Section title={'Editando: '+selected.name}><form className="editor-form" onSubmit={editDocument}><label>Nome<input name="name" defaultValue={selected.name}/></label><label>Tipo<input name="type" defaultValue={selected.document_type}/></label><textarea name="content" defaultValue={selected.content||''} placeholder="Conteúdo do documento…"/><div><Button type="submit">Salvar alterações</Button><Button variant="secondary" type="button" onClick={()=>setView('viewer')}>Cancelar</Button></div></form></Section>}

{view==='history'&&selected&&<Section title="Histórico de atividades">{history.length?<div className="event-list">{history.map(e=><article key={e.id}><strong>{e.type}</strong><span>{new Date(e.created_at).toLocaleString('pt-BR')}</span><code>{JSON.stringify(e.payload)}</code></article>)}</div>:<StatePanel title="Sem histórico" message="Ainda não existem atividades registradas para este documento."/>}</Section>}
{view==='versions'&&selected&&<Section title="Versionamento" actions={<Button onClick={()=>setView('editor')}>Criar versão</Button>}>{versions.length?<div className="version-list">{versions.map(v=><article key={v.id}><strong>Versão {v.version_number}</strong><span>{new Date(v.created_at).toLocaleString('pt-BR')}</span><p>{v.content||'Sem conteúdo.'}</p><Button variant="secondary" onClick={()=>restoreVersion(v)}>Restaurar esta versão</Button></article>)}</div>:<StatePanel title="Sem versões" message="Este documento ainda não possui versões."/>}</Section>}

{view==='folders'&&<Section title="Pastas" actions={<Button onClick={()=>{setEditingFolder(null);setModal(true)}}>Nova pasta</Button>}><div className="card-grid">{folders.map(f=><article className="mini-card" key={f.id}><strong>{f.name}</strong><span>{f.parent_id?'Subpasta':'Pasta raiz'}</span><div><Button variant="secondary" onClick={()=>{setEditingFolder(f);setModal(true)}}>Renomear</Button><Button variant="danger" onClick={async()=>{await api.deleteFolder(f.id);load('folders')}}>Excluir</Button></div></article>)}</div></Section>}

{view==='profile'&&<Section title="Meu perfil"><form className="profile-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setUser(await api.updateMe({name:String(f.get('name')),phone:String(f.get('phone'))}))}}><label>Nome<input name="name" defaultValue={user.name}/></label><label>E-mail<input value={user.email} disabled/></label><label>Telefone<input name="phone" defaultValue={user.phone||''}/></label><Button>Salvar perfil</Button></form></Section>}

{view==='users'&&<Section title="Usuários">{user.role==='admin'?<div className="user-list">{users.map(u=><article key={u.id}><strong>{u.name}</strong><span>{u.email} · {u.role} · {u.status||'active'}</span>{u.id!==user.id&&<div><Button variant="secondary" onClick={async()=>{const role=prompt('Novo papel (user/manager/admin):',u.role);if(role) {await api.adminUpdateUser(u.id,{role});load('users')}}}>Alterar papel</Button><Button variant="secondary" onClick={async()=>{await api.adminUpdateUser(u.id,{status:u.status==='active'?'disabled':'active'});load('users')}}>{u.status==='active'?'Desativar':'Ativar'}</Button></div>}</article>)}</div>:<StatePanel title="Acesso restrito" message="Somente administradores podem gerenciar usuários."/>}</Section>}

{view==='groups'&&<Section title="Grupos" actions={<Button onClick={()=>setModal(true)}>Novo grupo</Button>}><div className="card-grid">{groups.map(g=><article className="mini-card" key={g.id}><strong>{g.name}</strong><span>{g.member_ids.length} membro(s)</span>{user.role==='admin'&&<div><Button variant="secondary" onClick={async()=>{const id=prompt('ID do usuário para adicionar:');if(id){await api.addMember(g.id,id);load('groups')}}}>Adicionar membro</Button>{g.member_ids.map(id=><Button key={id} variant="danger" onClick={async()=>{await api.removeMember(g.id,id);load('groups')}}>Remover {id.slice(0,6)}</Button>)}</div>}</article>)}</div></Section>}

{view==='permissions'&&selected&&permissions&&<Section title={'Permissões: '+selected.name}><p>Papel: <strong>{permissions.role}</strong></p><div className="permission-grid">{['read','write','delete','share'].map(a=><label key={a}><input type="checkbox" checked={permissions.actions.includes(a)} onChange={e=>setPermissions({...permissions,actions:e.target.checked?[...permissions.actions,a]:permissions.actions.filter(x=>x!==a)})}/> {a}</label>)}</div>{user.role==='admin'&&<><label>Papel<select value={permissions.role} onChange={e=>setPermissions({...permissions,role:e.target.value})}><option value="viewer">Visualizador</option><option value="editor">Editor</option><option value="manager">Gestor</option></select></label><Button onClick={async()=>{await api.setPermissions(selected.id,{role:permissions.role,actions:permissions.actions});setPermissions(await api.permissions(selected.id))}}>Salvar política</Button></>}}</Section>}
{view==='audit'&&<Section title="Auditoria"><div className="event-list">{events.map(e=><article key={e.id}><strong>{e.type}</strong><span>{new Date(e.created_at).toLocaleString('pt-BR')}</span><code>{JSON.stringify(e.payload)}</code></article>)}</div></Section>}
{view==='admin'&&<Section title="Administração"><p>Ferramentas administrativas disponíveis para o perfil atual.</p><div className="dashboard-grid"><div className="stat-card"><span>Usuários</span><strong>{users.length}</strong></div><div className="stat-card"><span>Grupos</span><strong>{groups.length}</strong></div><div className="stat-card"><span>Perfil</span><strong>{user.role}</strong></div></div><Button onClick={()=>setView('users')}>Gerenciar usuários</Button></Section>}
{view==='settings'&&<Section title="Configurações"><div className="settings-list"><article><strong>Tema</strong><span><button onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?'Usar claro':'Usar escuro'}</button></span></article><article><strong>API</strong><span>Configurada por VITE_API_BASE_URL</span></article><article><strong>Sessão</strong><span>{user.email}</span></article></div></Section>}
{notes.length>0&&<section className="notifications"><h2>Notificações</h2>{notes.slice(0,5).map(n=><div className="notification" key={n.id}><span>{n.message}</span>{!n.read&&<button onClick={async()=>{await api.readNotification(n.id);load('home')}}>Marcar como lida</button>}</div>)}</section>}
</main></div>

{modal&&<Modal title={view==='folders'?(editingFolder?'Renomear pasta':'Nova pasta'):view==='groups'?'Novo grupo':'Novo documento'} onClose={()=>setModal(false)}><form className="modal-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(view==='folders'){if(editingFolder)await api.updateFolder(editingFolder.id,{name:String(f.get('name'))});else await api.createFolder(String(f.get('name')),String(f.get('parent')||'')||null);setModal(false);load('folders')}else if(view==='groups'){await api.createGroup(String(f.get('name')));setModal(false);load('groups')}else await createDocument(e)}}>{view==='folders'||view==='groups'?<><label>Nome<input name="name" defaultValue={editingFolder?.name||''} required/></label>{view==='folders'&&!editingFolder&&<label>Pasta pai<select name="parent"><option value="">Raiz</option>{folders.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label>}</>:<><label>Nome<input name="name" required/></label><label>Tipo<input name="type" defaultValue="txt" required/></label><label>Pasta<select name="folder"><option value="">Sem pasta</option>{folders.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label>Conteúdo<textarea name="content" rows={8}/></label></>}<Button type="submit">Salvar</Button></form></Modal>}
</div>}
export default App;