import {FormEvent,useEffect,useMemo,useState} from 'react';
import {api,clearToken,getToken,saveSession,type DocumentItem,type Event,type Folder,type Group,type Notification,type User,type Version} from './services/api';import {Button,Icon,Modal,StatePanel} from './components/ui';
type View='home'|'documents'|'viewer'|'editor'|'create'|'history'|'versions'|'folders'|'favorites'|'recent'|'trash'|'search'|'advanced-search'|'profile'|'users'|'groups'|'permissions'|'audit'|'admin'|'settings';
function Auth({done}:{done:(u:User)=>void}){const[recovery,setRecovery]=useState(false),[register,setRegister]=useState(false),[name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState('');
async function submit(e:FormEvent){e.preventDefault();setError('');try{if(recovery){await api.recovery(email);return}const s=register?await api.register({name,email,password}):await api.login({email,password});saveSession(s);done(s.user)}catch(x){setError(x instanceof Error?x.message:'Não foi possível concluir.')}}return <main className="auth-shell"><section className="auth-card"><div className="brand-mark">K</div><p className="eyebrow">KORCZAK TECHNOLOGIES</p><h1>Korczak <span>Documents</span></h1>{error&&<div className="alert alert-error">{error}</div>}<form onSubmit={submit}>{!recovery&&register&&<label>Nome<input value={name} onChange={e=>setName(e.target.value)} required/></label>}<label>E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label>{!recovery&&<label>Senha<input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={12} required/></label>}<Button>{recovery?'Enviar recuperação':register?'Criar conta':'Entrar'}</Button></form><div className="auth-links"><button className="text-button" onClick={()=>setRecovery(!recovery)}>{recovery?'Voltar':'Recuperar acesso'}</button><button className="text-button" onClick={()=>{setRecovery(false);setRegister(!register)}}>{register?'Já tenho conta':'Criar conta'}</button></div></section></main>}
const nav:[View,string,string][]=[['home','Início','home'],['documents','Documentos','file'],['folders','Pastas','file'],['favorites','Favoritos','star'],['recent','Recentes','clock'],['trash','Lixeira','trash'],['search','Pesquisa','search'],['profile','Meu perfil','user'],['users','Usuários','user'],['groups','Grupos','user'],['permissions','Permissões','settings'],['audit','Auditoria','clock'],['admin','Administração','settings'],['settings','Configurações','settings']];
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="panel"><div className="panel-head"><h2>{title}</h2></div>{children}</section>}
function Table({docs,onSelect,onAction}:{docs:DocumentItem[];onSelect:(d:DocumentItem)=>void;onAction:(d:DocumentItem)=>void}){return docs.length?<div className="table-wrap"><table><thead><tr><th>Nome</th><th>Tipo</th><th>Atualizado</th><th>Status</th><th></th></tr></thead><tbody>{docs.map(d=><tr key={d.id}><td><button className="link-button" onClick={()=>onSelect(d)}><strong>{d.name}</strong></button></td><td>{d.document_type}</td><td>{new Date(d.updated_at).toLocaleString('pt-BR')}</td><td>{d.status==='deleted'?'Lixeira':'Ativo'}</td><td><button className="row-action" onClick={()=>onAction(d)}>{d.status==='deleted'?'↩':d.favorite?'★':'☆'}</button></td></tr>)}</tbody></table></div>:<StatePanel title="Nada por aqui" message="Nenhum item encontrado."/>}
function App(){const[user,setUser]=useState<User|null>(null),[boot,setBoot]=useState(true),[view,setView]=useState<View>('home'),[docs,setDocs]=useState<DocumentItem[]>([]),[selected,setSelected]=useState<DocumentItem|null>(null),[versions,setVersions]=useState<Version[]>([]),[folders,setFolders]=useState<Folder[]>([]),[users,setUsers]=useState<User[]>([]),[groups,setGroups]=useState<Group[]>([]),[events,setEvents]=useState<Event[]>([]),[notes,setNotes]=useState<Notification[]>([]),[permissions,setPermissions]=useState<{role:string;actions:string[]}|null>(null),[query,setQuery]=useState(''),[error,setError]=useState(''),[modal,setModal]=useState(false);
useEffect(()=>{if(!getToken()){setBoot(false);return}api.me().then(setUser).catch(clearToken).finally(()=>setBoot(false))},[]);
useEffect(()=>{if(user)load(view)},[user,view]);
async function load(v:View=view){try{setError('');if(['home','documents','favorites','trash'].includes(v)){setDocs(v==='favorites'?await api.favorites():v==='trash'?await api.trash():await api.documents())}if(v==='folders')setFolders(await api.folders());if(v==='recent')setEvents(await api.recent());if(v==='users'||v==='admin')setUsers(await api.users());if(v==='groups')setGroups(await api.groups());if(v==='audit')setEvents((await api.audit()).items);if(v==='home')setNotes(await api.notifications())}catch(x){setError(x instanceof Error?x.message:'Falha ao carregar dados.')}}
async function select(d:DocumentItem,v:View='viewer'){setSelected(d);await api.open(d.id).catch(()=>{});setView(v);if(v==='history'||v==='versions')setVersions(await api.versions(d.id));if(v==='permissions')setPermissions(await api.permissions(d.id))}
async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{const d=await api.createDocument({name:String(f.get('name')),document_type:String(f.get('type')),folder_id:String(f.get('folder')||'')||null,content:String(f.get('content')||'')});setModal(false);setSelected(d);setView('viewer');await load('documents')}catch(x){setError(x instanceof Error?x.message:'Não foi possível criar.')}}
async function edit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;const f=new FormData(e.currentTarget);try{await api.updateDocument(selected.id,{name:String(f.get('name')),document_type:String(f.get('type'))});setSelected(await api.document(selected.id));setView('viewer')}catch(x){setError(x instanceof Error?x.message:'Não foi possível salvar.')}}
async function newVersion(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;const f=new FormData(e.currentTarget);await api.createVersion(selected.id,String(f.get('content')||''));setVersions(await api.versions(selected.id));setView('versions')}
if(boot)return <StatePanel title="Iniciando" message="Preparando o Korczak Documents…"/>;if(!user)return <Auth done={setUser}/>;
const shown=useMemo(()=>{if(view==='search'||view==='advanced-search')return docs.filter(d=>d.name.toLowerCase().includes(query.toLowerCase()));return docs},[docs,view,query]);
const title=nav.find(n=>n[0]===view)?.[1]||'Korczak Documents';
const documentPanel=<Section title={view==='favorites'?'Favoritos':view==='trash'?'Lixeira':'Documentos'}><Table docs={shown} onSelect={d=>select(d)} onAction={async d=>{try{if(d.status==='deleted')await api.restore(d.id);else await api.favorite(d.id,!d.favorite);await load(view)}catch(x){setError(x instanceof Error?x.message:'Operação não concluída.')}}}/></Section>;
return <div className="app-shell"><aside className="sidebar"><div className="side-brand"><div className="brand-mark small">K</div><div><strong>Korczak</strong><span>Documents</span></div></div><nav>{nav.map(n=><button className={'nav-item '+(view===n[0]?'active':'')} onClick={()=>setView(n[0])} key={n[0]}><Icon name={n[2]}/><span>{n[1]}</span></button>)}</nav><div className="sidebar-bottom"><button className="nav-item" onClick={()=>{clearToken();setUser(null)}}>↪ Sair</button></div></aside><div className="main-shell"><header className="topbar"><div className="mobile-brand"><b>Korczak Documents</b></div><div className="top-search"><Icon name="search"/><input value={query} onChange={e=>{setQuery(e.target.value);setView('search')}} placeholder="Pesquisar documentos…"/></div><button className="avatar" onClick={()=>setView('profile')}>{user.name[0]}</button></header><main className="content"><div className="page-head"><div><p className="eyebrow">KORCZAK DOCUMENTS</p><h1>{title}</h1></div>{['documents','home'].includes(view)&&<Button onClick={()=>setModal(true)}><Icon name="plus"/>Novo documento</Button>}</div>{error&&<div className="alert alert-error">{error}<button onClick={()=>load(view)}>Tentar novamente</button></div>}
{view==='home'&&<section className="dashboard-grid"><div className="welcome-card"><p className="eyebrow">DASHBOARD</p><h2>Olá, {user.name.split(' ')[0]}.</h2><p>Seu espaço de documentos em um só lugar.</p><Button onClick={()=>setModal(true)}>Criar documento</Button></div><div className="stat-card"><span>Documentos</span><strong>{docs.length}</strong></div><div className="stat-card"><span>Favoritos</span><strong>{docs.filter(d=>d.favorite).length}</strong></div><div className="stat-card"><span>Notificações</span><strong>{notes.filter(n=>!n.read).length}</strong></div></section>}
{view==='documents'&&documentPanel}{view==='favorites'&&documentPanel}{view==='trash'&&documentPanel}
{view==='search'&&<Section title="Pesquisa global">{documentPanel}</Section>}{view==='advanced-search'&&<Section title="Pesquisa avançada"><div className="advanced-grid"><label>Termo<input value={query} onChange={e=>setQuery(e.target.value)}/></label><label>Pasta<select onChange={e=>api.search(query,e.target.value).then(setDocs)}><option value="">Todas</option>{folders.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label></div>{documentPanel}</Section>}
{view==='viewer'&&selected&&<Section title={selected.name}><div className="document-toolbar"><Button variant="secondary" onClick={()=>setView('editor')}>Editar</Button><Button variant="secondary" onClick={()=>select(selected,'versions')}>Versionamento</Button><Button variant="secondary" onClick={()=>select(selected,'history')}>Histórico</Button><Button variant="secondary" onClick={()=>select(selected,'permissions')}>Permissões</Button><Button variant="danger" onClick={async()=>{await api.deleteDocument(selected.id);setView('documents');load('documents')}}>Mover para lixeira</Button></div><div className="document-view"><p>Documento: <strong>{selected.name}</strong></p><p>Tipo: {selected.document_type}</p><p>Atualizado: {new Date(selected.updated_at).toLocaleString('pt-BR')}</p></div></Section>}
{view==='editor'&&selected&&<Section title="Editor"><form className="editor-form" onSubmit={newVersion}><textarea name="content" defaultValue="" placeholder="Edite o conteúdo do documento…"/><div><Button type="submit">Salvar nova versão</Button><Button variant="secondary" type="button" onClick={()=>setView('viewer')}>Cancelar</Button></div></form></Section>}
{view==='create'&&<Section title="Criação de documento"><Button onClick={()=>setModal(true)}>Abrir criação</Button></Section>}
{(view==='history'||view==='versions')&&selected&&<Section title={view==='history'?'Histórico':'Versionamento'}>{versions.length?<div className="version-list">{versions.map(v=><article key={v.id}><strong>Versão {v.version_number}</strong><span>{new Date(v.created_at).toLocaleString('pt-BR')}</span><p>{v.content||'Sem conteúdo.'}</p></article>)}</div>:<StatePanel title="Sem versões" message="Este documento ainda não possui versões registradas."/>}</Section>}
{view==='folders'&&<Section title="Pastas"><Button onClick={()=>setModal(true)}>Nova pasta</Button><div className="card-grid">{folders.map(f=><article className="mini-card" key={f.id}><strong>{f.name}</strong><span>{f.parent_id?'Subpasta':'Pasta raiz'}</span></article>)}</div></Section>}
{view==='recent'&&<Section title="Recentes"><div className="event-list">{events.map(e=><article key={e.id}><strong>{e.type}</strong><span>{new Date(e.created_at).toLocaleString('pt-BR')}</span></article>)}</div></Section>}
{view==='profile'&&<Section title="Meu perfil"><form className="profile-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setUser(await api.updateMe({name:String(f.get('name')),phone:String(f.get('phone'))}))}}><label>Nome<input name="name" defaultValue={user.name}/></label><label>E-mail<input value={user.email} disabled/></label><label>Telefone<input name="phone" defaultValue={user.phone||''}/></label><Button>Salvar perfil</Button></form></Section>}
{view==='users'&&<Section title="Usuários">{users.length?<Table docs={[]} onSelect={()=>{}} onAction={()=>{}}/>:<StatePanel title="Sem acesso" message="A listagem de usuários exige perfil administrativo."/>}<div className="user-list">{users.map(u=><article key={u.id}><strong>{u.name}</strong><span>{u.email} • {u.role}</span></article>)}</div></Section>}
{view==='groups'&&<Section title="Grupos"><Button onClick={()=>setModal(true)}>Novo grupo</Button><div className="card-grid">{groups.map(g=><article className="mini-card" key={g.id}><strong>{g.name}</strong><span>{g.member_ids.length} membro(s)</span></article>)}</div></Section>}
{view==='permissions'&&selected&&permissions&&<Section title="Permissões de documento"><p>Papel atual: <strong>{permissions.role}</strong></p><p>Ações: {permissions.actions.join(', ')}</p><Button onClick={async()=>{await api.setPermissions(selected.id,{role:'editor',actions:['read','write']});setPermissions(await api.permissions(selected.id))}}>Aplicar política de edição</Button></Section>}
{view==='audit'&&<Section title="Auditoria"><div className="event-list">{events.map(e=><article key={e.id}><strong>{e.type}</strong><span>{new Date(e.created_at).toLocaleString('pt-BR')}</span><code>{JSON.stringify(e.payload)}</code></article>)}</div></Section>}
{view==='admin'&&<Section title="Administração"><p>Área administrativa do usuário.</p><div className="stat-card"><span>Usuários carregados</span><strong>{users.length}</strong></div></Section>}
{view==='settings'&&<Section title="Configurações"><div className="settings-list"><article><strong>Interface</strong><span>Korczak Documents • tema escuro</span></article><article><strong>API</strong><span>Conexão configurável por VITE_API_BASE_URL</span></article><article><strong>Conta</strong><span>{user.email}</span></article></div></Section>}
{notes.length>0&&<section className="notifications"><h2>Notificações</h2>{notes.slice(0,5).map(n=><div className="notification" key={n.id}><span>{n.message}</span>{!n.read&&<button onClick={async()=>{await api.readNotification(n.id);load(view)}}>Lida</button>}</div>)}</section>}
</main></div>{modal&&<Modal title={view==='folders'?'Nova pasta':view==='groups'?'Novo grupo':'Novo documento'} onClose={()=>setModal(false)}><form className="modal-form" onSubmit={async e=>{if(view==='folders'){e.preventDefault();const f=new FormData(e.currentTarget);await api.createFolder(String(f.get('name')));setModal(false);load('folders')}else if(view==='groups'){e.preventDefault();const f=new FormData(e.currentTarget);await api.createGroup(String(f.get('name')));setModal(false);load('groups')}else create(e)}}>{view==='folders'||view==='groups'?<label>Nome<input name="name" required/></label>:<><label>Nome<input name="name" required/></label><label>Tipo<input name="type" defaultValue="txt" required/></label><label>Pasta<select name="folder"><option value="">Sem pasta</option>{folders.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label>Conteúdo<textarea name="content" rows={8}/></label></>}<Button type="submit">Salvar</Button></form></Modal>}</div>}
export default App;